server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:5500
              - http://3.209.159.160:30080
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/users/**
        - id: ms-paquetes
          uri: lb://ms-paquetes
          predicates:
            - Path=/api/tourist-packages/**,/api/destinations/**,/api/categories/**,/api/package-types/**,/api/seasons/**,/api/package-services/**,/api/promotions/**,/api/statuses/**
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/api/bookings/**
        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/payments/**
        - id: ms-seguimiento
          uri: lb://ms-seguimiento
          predicates:
            - Path=/api/tracking/**
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reports/**




