apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagos
  namespace: travelagency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagos
  template:
    metadata:
      labels:
        app: ms-pagos
    spec:
      containers:
        - name: ms-pagos
          image: dialtamiranoh/travelagency-ms-pagos:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://ms-pagos-postgres:5432/ta_ms_pagos
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: EUREKA_HOST
              value: eureka-service
            - name: EUREKA_HOST
              value: eureka-service
---
apiVersion: v1
kind: Service
metadata:
  name: ms-pagos
  namespace: travelagency
spec:
  selector:
    app: ms-pagos
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP


