apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: travelagency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: dialtamiranoh/travelagency-api-gateway:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka
            - name: EUREKA_HOST
              value: eureka-service
            - name: EUREKA_HOST
              value: eureka-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: travelagency
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
  type: NodePort


