apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: travelagency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: dialtamiranoh/travelagency-eureka-service:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: travelagency
spec:
  selector:
    app: eureka-service
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
